apimServiceName: brd-apim-prd
namedValues:
  - name: environment
    properties:
      displayName: environment
      value: https://www.bing.com
  - name: demo
    properties:
      displayName: demo
      value: demo message new again again
  - name: TimeNow
    properties:
      displayName: TimeNow
      value: "@(DateTime2.Now.ToString())"
  - name: testSecret
    properties:
      displayName: testSecret
      value: "{#testSecretValue#}"
  - name: signingKey
    properties:
      displayName: signingKey
      keyVault: 
        secretIdentifier: https://brd-scus-apimdemo-kv-prd.vault.azure.net/secrets/APIM-signing-key
  - name: 639121f85ddd1701d02ea23f
    properties:
      displayName: Logger-Credentials--639121f85ddd1701d02ea240
      value: "{#appInsightsLoggerKey#}"
loggers:
    - name: brd-scus-apim-ai-dev
      properties:
        loggerType: applicationInsights
        description: App insights logger info
        resourceId: "/subscriptions/ac81efbd-2d16-4829-9c4c-228a17db1f32/resourceGroups/brd-scus-apiopsdemo-rg-prd/providers/microsoft.insights/components/brd-scus-apim-ai-prd"
        credentials:
          instrumentationKey: "{{Logger-Credentials--639121f85ddd1701d02ea240}}"
        isBuffered: true
diagnostics:
    - name: applicationinsights
      properties:
        verbosity: Error
        loggerId: "/subscriptions/ac81efbd-2d16-4829-9c4c-228a17db1f32/resourceGroups/brd-scus-apiopsdemo-rg-dev/providers/Microsoft.ApiManagement/service/brd-apim-prd/loggers/red-scus-apim-ai-dev"
apis:
  - name: "basic-calculator"
    properties:
      serviceUrl: "http://calcapi.cloudapp.net/api/from-config/"
    diagnostics:
      - name: applicationinsights
        properties:
          verbosity: Error
          loggerId: "/subscriptions/ac81efbd-2d16-4829-9c4c-228a17db1f32/resourceGroups/brd-scus-apiopsdemo-rg-dev/providers/Microsoft.ApiManagement/service/brd-apim-prd/loggers/red-scus-apim-ai-dev"
