trigger:
  branches:
    include:
      - main
  paths:
    include:
      - 'devportal-artifacts/**'

parameters:
  - name: OUTPUT_FOLDER_PATH
    type: string
    displayName: Folder where the artifacts reside
    default: devportal-artifacts

variables:
  - group: apim-automation
  - name: System.Debug
    value: true

stages:
- stage: release_dev
  displayName: 'Release to Dev'
  jobs:
    - job: push_changes_to_Dev
      displayName: 'Push changes to Dev'
      pool:
        vmImage: 'ubuntu-latest'
      steps:
      - template: ./run-release-with-env.yaml
        parameters:
          ENVIRONMENT: 'Dev'
          OUTPUT_FOLDER_PATH: ${{ parameters.OUTPUT_FOLDER_PATH }}

- stage: release_prod
  displayName: 'Release to Prod'
  jobs:
    - deployment: push_changes_to_Prod
      displayName: 'Push changes to Prod'
      pool:
        vmImage: 'ubuntu-latest'
      environment: 'Prod'
      strategy:
        # default deployment strategy, more coming...
        runOnce:
          deploy:
            steps:
            - template: ./run-release-with-env.yaml
              parameters:
                ENVIRONMENT: 'Prod'
                OUTPUT_FOLDER_PATH: ${{ parameters.OUTPUT_FOLDER_PATH }}