trigger:
  branches:
    include:
      - main
  paths:
    include:
      - 'devportal-artifacts/**'

pr:
  branches:
    include:
      - main
  paths:
    include:
      - 'devportal-artifacts/**'

parameters:
  - name: OUTPUT_FOLDER_PATH
    type: string
    displayName: Folder where the artifacts reside
    default: devportal-artifacts

jobs:
- job: release-dev
  displayName: 'Release to Dev'
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - template: ./run-release-with-env.yml
    parameters:
      ENVIRONMENT: 'Dev'
      OUTPUT_FOLDER_PATH: ${{ parameters.OUTPUT_FOLDER_PATH }}

- job: release-stage
  displayName: 'Release to Stage'
  dependsOn: release-dev
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - template: ./run-release-with-env.yml
    parameters:
      ENVIRONMENT: 'Prod'
      OUTPUT_FOLDER_PATH: ${{ parameters.OUTPUT_FOLDER_PATH }}
