trigger:
  branches:
    include:
      - main
  paths:
    include:
      - 'devportal-artifacts/**'

pr:
  branches:
    include:
      - main
  paths:
    include:
      - 'devportal-artifacts/**'

parameters:
  - name: OUTPUT_FOLDER_PATH
    type: string
    displayName: Folder where the artifacts reside
    default: devportal-artifacts

jobs:
- job: release_dev
  displayName: 'Release to Dev'
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - template: ./run-release-with-env.yaml
    parameters:
      ENVIRONMENT: 'Dev'
      OUTPUT_FOLDER_PATH: ${{ parameters.OUTPUT_FOLDER_PATH }}

- deployment: release_stage
  displayName: 'Release to Stage'
  dependsOn: release_dev
  pool:
    vmImage: 'ubuntu-latest'
  environment: 'Prod'
  strategy:
    # default deployment strategy, more coming...
    runOnce:
      deploy:
        steps:
        - template: ./run-release-with-env.yaml
          parameters:
            ENVIRONMENT: 'Prod'
            OUTPUT_FOLDER_PATH: ${{ parameters.OUTPUT_FOLDER_PATH }}
