openapi: 3.0.1
info:
  title: red-anyonecancode-web
  description: ''
  version: '1.0'
servers:
  - url: https://brd-apim-dev.azure-api.net/anyone
paths:
  /*:
    delete:
      summary: red-anyonecancode-web_DELETE
      description: red-anyonecancode-web_DELETE
      operationId: 649f3bd4a84333bc56b1e8c7
      responses:
        '200':
          description: ''
    head:
      summary: red-anyonecancode-web_HEAD
      description: red-anyonecancode-web_HEAD
      operationId: 649f3bd45bfd612ae472f90e
      responses:
        '200':
          description: ''
    trace:
      summary: red-anyonecancode-web_TRACE
      description: red-anyonecancode-web_TRACE
      operationId: 649f3bd4e5c43f853963a8cc
      responses:
        '200':
          description: ''
    patch:
      summary: red-anyonecancode-web_PATCH
      description: red-anyonecancode-web_PATCH
      operationId: 649f3bd4ca588aaceba88049
      responses:
        '200':
          description: ''
    put:
      summary: red-anyonecancode-web_PUT
      description: red-anyonecancode-web_PUT
      operationId: 649f3bd428b07a0031890c52
      responses:
        '200':
          description: ''
    post:
      summary: red-anyonecancode-web_POST
      description: red-anyonecancode-web_POST
      operationId: 649f3bd4dc5c34c952ebcd01
      responses:
        '200':
          description: ''
    get:
      summary: red-anyonecancode-web_GET
      description: red-anyonecancode-web_GET
      operationId: 649f3bd4c3b1f620ebf93770
      responses:
        '200':
          description: ''
    options:
      summary: red-anyonecancode-web_OPTIONS
      description: red-anyonecancode-web_OPTIONS
      operationId: 649f3bd467b3ff9c0e376d11
      responses:
        '200':
          description: ''
components:
  securitySchemes:
    apiKeyHeader:
      type: apiKey
      name: Ocp-Apim-Subscription-Key
      in: header
    apiKeyQuery:
      type: apiKey
      name: subscription-key
      in: query
security:
  - apiKeyHeader: [ ]
  - apiKeyQuery: [ ]